config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :pops
  root 'pops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_one_attached :image
    has_one_attached :zzimage
    has_one_attached :runimage
end

app/models/pop.rb
class Pop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
    @time = Time.now.strftime('%S')
   
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
   
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :image, :kind, :pr, :user_id, :letter, :letter2, :letter3, :zzimage, :runimage, :hp, :pp, :yobi)
    end
end

app/controllers/pops_controller.rb
class PopsController < ApplicationController
  before_action :set_pop, only: %i[ show edit update destroy ]

  # GET /pops or /pops.json
  def index
    @pops = Pop.all
  end

  # GET /pops/1 or /pops/1.json
  def show
  end

  # GET /pops/new
  def new
    @pop = Pop.new
  end

  # GET /pops/1/edit
  def edit
  end

  # POST /pops or /pops.json
  def create
    @pop = Pop.new(pop_params)

    respond_to do |format|
      if @pop.save
        format.html { redirect_to pop_url(@pop), notice: "Pop was successfully created." }
        format.json { render :show, status: :created, location: @pop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pops/1 or /pops/1.json
  def update
    respond_to do |format|
      if @pop.update(pop_params)
        format.html { redirect_to pop_url(@pop), notice: "Pop was successfully updated." }
        format.json { render :show, status: :ok, location: @pop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pops/1 or /pops/1.json
  def destroy
    @pop.destroy

    respond_to do |format|
      format.html { redirect_to pops_url, notice: "Pop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pop
      @pop = Pop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pop_params
      params.require(:pop).permit(:pop)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/pops_helper.rb
module PopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'shared/header'%>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= form.text_field :kind %>
  </div>

  <div class="field">
    <%= form.label :pr %>
    <%= form.text_area :pr %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :letter %>
    <%= form.text_area :letter %>
  </div>

  <div class="field">
    <%= form.label :letter2 %>
    <%= form.text_area :letter2 %>
  </div>

  <div class="field">
    <%= form.label :letter3 %>
    <%= form.text_area :letter3 %>
  </div>

  <div class="field">
    <%= form.label :zzimage %>
    <%= form.file_field :zzimage %>
  </div>

  <div class="field">
    <%= form.label :runimage %>
    <%= form.file_field :runimage %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp %>
  </div>

  <div class="field">
    <%= form.label :pp %>
    <%= form.number_field :pp %>
  </div>

  <div class="field">
    <%= form.label :yobi %>
    <%= form.number_field :yobi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>
<!--headerのロゴリンクを、dogrun/indexページにする
-->
<h1>Pets</h1>
<%= @time %>



<!--<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>写真</th>
      <th>性格</th>
      <th>コメント</th>
      <th>User</th>
      <th>Letter</th>
      <th>Letter2</th>
      <th>Letter3</th>
      <th>Zzimage</th>
      <th>Runimage</th>
      <th colspan="3"></th>
    </tr>
  </thead>-->

  <!--<tbody>-->
  <div class = "room-show-image">
    <% @pets.each do |pet| %>
      
        <p><%= pet.name %></p>
        <% if pet.id == 1 %>
          <%= image_tag "img1.jpg" , class:'fluffy' %><p>元気</p>
        <% elsif pet.id == 2%>
          <%= image_tag "https://www.pokemon.co.jp/PostImages/ba62cb498d3106e7745af6238a98e34cbaad5dc2.jpg" , class:'fluffy' %><p>2da</p>
        <% elsif pet.id == 3%>
          <%= image_tag "https://scontent.fkix2-2.fna.fbcdn.net/v/t39.30808-6/293686907_5285748151518665_6292159894868406269_n.jpg?stp=cp1_dst-jpg&_nc_cat=103&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=gyuzHLb86fYAX8cThTC&_nc_ht=scontent.fkix2-2.fna&oh=00_AT_J7wn8VyYZ0x08oJUxvONy4yPrsoQ6JJ30M4kB1frgAA&oe=62D65A3D" , class:'fluffy' %><p>2da</p>
        <% elsif pet.id == 4%>
          <%= image_tag "img1.jpg" , class:'fluffy' %><p>2da</p>
        <% else %>
         
        <% end %>


      
    </div>
        <p><%= pet.kind %><p>
        <p><%= pet.pr %><p>
       <td><%= pet.user_id %></td>
        <td><%= pet.letter %></td>
        <td><%= pet.letter2 %></td>
        <td><%= pet.letter3 %></td>
        <td><%= pet.id %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="room-show-image">
 		<%= image_tag @pet.image ,class:'dogrun-show-image'%>
	</div>

<p>
  <strong>名前:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>性格:</strong>
  <%= @pet.kind %>
</p>

<p>
  <strong>コメント:</strong>
  <%= @pet.pr %>
</p>

<p>
  <strong>手紙１:</strong>
  <%= @pet.letter %>
</p>

<p>
  <strong>手紙２:</strong>
  <%= @pet.letter2 %>
</p>

<p>
  <strong>手紙３:</strong>
  <%= @pet.letter3 %>
</p>

<div class="room-show-image">
 		<%= image_tag @pet.zzimage ,class:'dogrun-show-image'%>
	</div>

<div class="room-show-image">
 		<%= image_tag @pet.runimage ,class:'dogrun-show-image'%>
	</div>

<%= link_to '編集', edit_pet_path(@pet) %> |
<%= link_to 'トップ', pets_path %>

app/views/pops/_form.html.erb
<%= form_with(model: pop) do |form| %>
  <% if pop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pop.errors.count, "error") %> prohibited this pop from being saved:</h2>

      <ul>
        <% pop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pop %>
    <%= form.text_field :pop %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pops/edit.html.erb
<h1>Editing Pop</h1>

<%= render 'form', pop: @pop %>

<%= link_to 'Show', @pop %> |
<%= link_to 'Back', pops_path %>

app/views/pops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pops</h1>

<table>
  <thead>
    <tr>
      <th>Pop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pops.each do |pop| %>
      <tr>
        <td><%= pop.pop %></td>
        <td><%= link_to 'Show', pop %></td>
        <td><%= link_to 'Edit', edit_pop_path(pop) %></td>
        <td><%= link_to 'Destroy', pop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pop', new_pop_path %>

app/views/pops/new.html.erb
<h1>New Pop</h1>

<%= render 'form', pop: @pop %>

<%= link_to 'Back', pops_path %>

app/views/pops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pop:</strong>
  <%= @pop.pop %>
</p>

<%= link_to 'Edit', edit_pop_path(@pop) %> |
<%= link_to 'Back', pops_path %>

app/views/shared/_header.html.erb
<h1>Yayocchi</h1>